@startuml
title Secuencia – Venta con Receta

actor Empleado
participant "UI" as UI
participant "VentaController" as VC
participant "VentaService" as VS
participant "InventarioService" as IS
database "DB" as DB

Empleado -> UI : Ingresa venta (receta, items)
UI -> VC : POST /ventas
VC -> VS : procesarVenta(dto)
VS -> IS : verificarStock(items)
IS -> DB : SELECT stock
DB --> IS : Cantidades disponibles
IS --> VS : OK
VS -> DB : INSERT Venta + DetalleVenta
VS -> IS : descontarStock(items)
IS -> DB : UPDATE stock
DB --> IS : Actualizacion de stock
IS--> VS: OK
VS --> VC : Venta registrada
VC --> UI : Confirmación
UI --> Empleado : Ticket generado
@enduml
